[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pwndbgex"
version = "0.0.1"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
include = ["pwndbgex"]
exclude = []
namespaces = false
